#!/usr/bin/env python3
import argparse
import logging
from libs.utils import *

parser = argparse.ArgumentParser(description="HSBC X-Ray project.")
parser.add_argument("-q", "--quiet", help="Quiet mode.", action="store_true", default=False)
parser.add_argument("--uri", help="MongoDB database URI.", type=str, default="mongodb://localhost:27017/")
args = parser.parse_args()

logger = logging.getLogger(__name__)
if args.quiet:
    logger.setLevel(logging.FATAL)