#!/usr/bin/env python3
import argparse
import logging
from libs.utils import *
from libs.framework import Framework
from pymongo import MongoClient

parser = argparse.ArgumentParser(description="HSBC X-Ray project.")
parser.add_argument("-q", "--quiet", help="Quiet mode.", action="store_true", default=False)
parser.add_argument("-s", "--checkset", help="Check set to run.", type=str, default="default")
parser.add_argument("-o", "--output", help="Output folder path.", type=str, default="output/")
parser.add_argument("--uri", help="MongoDB database URI.", type=str, default="mongodb://localhost:27017/")
args = parser.parse_args()

logger = logging.getLogger(__name__)
if args.quiet:
    logger.setLevel(logging.FATAL)

def main():
    client = MongoClient(args.uri)  # Initialize MongoDB client
    config = load_config()
    checkset = args.checkset
    framework = Framework(config)
    framework.run_checks(checkset, client, output_folder=args.output)
    framework.output_results(output_folder=args.output)

if __name__ == "__main__":
    main()